Módulo 3 Listo aunque con errores:
npm start

> siat@1.0.0 start
> electron .

App threw an error during load
Error: The module '\\?\C:\SIAT\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 132. This version of Node.js requires
NODE_MODULE_VERSION 145. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2617)
    at Module._extensions..node (node:internal/modules/cjs/loader:1980:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2617)
    at Module.load (node:internal/modules/cjs/loader:1540:32)
    at Module._load (node:internal/modules/cjs/loader:1342:12)
    at c._load (node:electron/js2c/node_init:2:17999)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1563:12)
    at require (node:internal/modules/helpers:152:16)
    at bindings (C:\SIAT\node_modules\bindings\bindings.js:112:48)

    Se usará codex de chat gpt para buscar solución.